package org.markupcarve.carve

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Reads the provenance headers the bundle build scripts write.
 *
 * `tools/build-carve-bundle.sh` and `tools/build-lsp-bundle.sh` have always
 * stamped each bundle with the commit it was built from, and until now nothing
 * ever read one back. A recorded provenance no check consumes looks like
 * traceability and cannot fail - the shape catalogued in markup-carve/carve#755
 * - and it is how `carve-js dependency commit unknown` came to sit in a
 * committed bundle: the producer degraded when carve-lsp moved its engine to
 * the registry, and there was no consumer to notice (#62).
 *
 * This is the local, offline half: the header must exist, be well formed, name
 * a real reference, and agree with the sibling `lsp/VERSION` file. Whether those
 * commits are still current upstream is a networked question and lives in
 * `.github/workflows/engine-drift.yml`, which parses the same three lines.
 *
 * Both files are read from the SOURCE TREE rather than the classpath on
 * purpose: `lsp/VERSION` is a build-script output that has to be checked against
 * its own bundle, and comparing two files that were regenerated together is the
 * point.
 */
class CarveBundleProvenanceTest {

    private val sha = Regex("^[0-9a-f]{40}$")

    @Test
    fun previewBundleRecordsTheCarveJsCommitItWasBuiltFrom() {
        val header = headerOf(resource("js/carve.iife.js"))

        assertTrue(
            "carve.iife.js has lost its generator line - rebuild it with " +
                "tools/build-carve-bundle.sh:\n$header",
            header.any { it.contains("Generated by tools/build-carve-bundle.sh") },
        )

        val commit = capture(header, Regex("Bundled from markup-carve/carve-js commit (\\S+)"))
            ?: throw AssertionError(
                "carve.iife.js records no carve-js commit. The header is written by " +
                    "tools/build-carve-bundle.sh; rebuild rather than hand-editing:\n$header",
            )
        assertTrue(
            "carve.iife.js records '$commit' as its carve-js commit, which is not a 40-character " +
                "sha. A placeholder here is exactly the unreadable provenance this test exists " +
                "to reject.",
            sha.matches(commit),
        )
        assertTrue(
            "carve.iife.js records no build timestamp:\n$header",
            capture(header, BUILT_AT) != null,
        )
    }

    @Test
    fun languageServerBundleRecordsBothItsOwnCommitAndTheEngineItCarries() {
        val header = headerOf(resource("lsp/server.js"))

        val lspCommit = capture(header, Regex("Bundled from markup-carve/carve-lsp commit (\\S+)"))
            ?: throw AssertionError("lsp/server.js records no carve-lsp commit:\n$header")
        assertTrue(
            "lsp/server.js records '$lspCommit' as its carve-lsp commit, which is not a 40-character sha.",
            sha.matches(lspCommit),
        )

        // Two legitimate shapes, because carve-lsp has used both: a git
        // dependency (`commit <sha>`) and, since it pinned the engine exactly,
        // a published one (`npm <version>`). Anything else - and in particular
        // the literal `unknown` this field used to degrade to - is a failure.
        val engine = capture(header, Regex("carve-js dependency (.+)"))?.trim()
            ?: throw AssertionError("lsp/server.js records no carve-js dependency:\n$header")
        assertTrue(
            "lsp/server.js records its carve-js dependency as '$engine'. It must be " +
                "'commit <40-hex>' or 'npm <version>' - a placeholder means the build script's " +
                "lockfile probe stopped matching and the provenance is no longer readable.",
            ENGINE_REF.matches(engine),
        )
    }

    /**
     * A sha says which commit; it does not say whether that commit was ever
     * released. Nothing in this repo asked the difference, and so 0.1.5 shipped
     * a language server built from `ef1ca246` - twelve commits past `v0.1.3`,
     * thirty-eight short of main, a revision no carve-lsp user could install -
     * while `lsp/VERSION` recorded that pin perfectly accurately (#110).
     *
     * So the build script now derives a release name for each half from the
     * upstream that owns it, and this is the consumer that makes the field
     * load-bearing: `none` is what an untagged checkout produces, and a bundle
     * built from one cannot be committed past here.
     *
     * The engine's release name covers BOTH vendored engines, not just this
     * one: the test below pins the preview bundle to the same carve-js commit,
     * so naming that commit's tag once names it for the pair.
     */
    @Test
    fun bothVendoredHalvesNameTheReleaseTheyWereBuiltFrom() {
        val header = headerOf(resource("lsp/server.js"))

        for ((field, what) in listOf(
            "carve-lsp release" to "the language server itself",
            "carve-js release" to "the engine it carries",
        )) {
            val release = capture(header, Regex("$field (.+)"))?.trim()
                ?: throw AssertionError(
                    "lsp/server.js records no '$field'. tools/build-lsp-bundle.sh writes it; " +
                        "rebuild rather than hand-editing:\n$header",
                )
            assertTrue(
                "lsp/server.js names '$release' as the release of $what. A vendored bundle has " +
                    "to come from a published release - 'none' means the checkout it was built " +
                    "from sat on no tag, which is the unreleased-server bug this field exists " +
                    "to make visible. Check out the release tag and rebuild.",
                RELEASE_REF.matches(release),
            )
        }
    }

    /**
     * The plugin ships the engine twice - carve.iife.js for the preview pane and
     * HTML export, and a second copy inlined into the language server - and a
     * user editing one document is looking at both at once. When they disagree,
     * nothing on screen says which half is right.
     *
     * The two used to be built by two scripts that choose an engine two
     * different ways, so they were free to drift: they shipped 42 carve-js
     * commits apart, built 21 seconds apart, and the two tests above both passed
     * the whole time. Each reads one file (the third compares a bundle against
     * its own sidecar), so nothing here related one bundle's engine to the
     * other's - provenance recorded, and the one question it exists to answer
     * never asked. See #93, and markup-carve/carve#755 for the shape.
     *
     * tools/build-engine-bundles.sh is what keeps this true: it takes the
     * revision once and builds both from it.
     */
    @Test
    fun bothBundlesCarryTheSameCarveJsCommit() {
        val previewHeader = headerOf(resource("js/carve.iife.js"))
        val serverHeader = headerOf(resource("lsp/server.js"))

        val preview = capture(previewHeader, Regex("Bundled from markup-carve/carve-js commit (\\S+)"))
            ?: throw AssertionError("carve.iife.js records no carve-js commit:\n$previewHeader")
        val engine = capture(serverHeader, Regex("carve-js dependency (.+)"))?.trim()
            ?: throw AssertionError("lsp/server.js records no carve-js dependency:\n$serverHeader")

        // A published reference is a legitimate thing for carve-lsp itself to
        // pin, and the test above accepts it - but `npm 0.1.4` and a 40-hex
        // commit cannot be compared, so a bundle vendored HERE has to name the
        // commit. That is what tools/build-engine-bundles.sh writes.
        val server = capture(listOf(engine), Regex("^commit ([0-9a-f]{40})$"))
            ?: throw AssertionError(
                "lsp/server.js carries carve-js as '$engine', which cannot be compared against the " +
                    "preview bundle's commit $preview. Rebuild the pair with " +
                    "tools/build-engine-bundles.sh, which links the language server against an " +
                    "explicit carve-js commit for exactly this reason.",
            )

        assertEquals(
            "The two vendored engines are different builds of carve-js: the preview pane runs " +
                "$preview and the language server carries $server. They render the same document " +
                "for the same user, so they have to be one revision. Rebuild both with " +
                "'tools/build-engine-bundles.sh ../carve-js ../carve-lsp' and commit the pair.",
            preview,
            server,
        )
    }

    @Test
    fun theVersionFileAgreesWithTheBundleItWasWrittenBeside() {
        val header = headerOf(resource("lsp/server.js"))
        val version = resource("lsp/VERSION").readLines().filter { it.isNotBlank() }

        val fromVersion = version.mapNotNull { line ->
            val (key, value) = line.split(' ', limit = 2).let { it[0] to it.getOrElse(1) { "" } }
            if (key == "built") null else key to value.trim()
        }.toMap()

        assertEquals(
            "lsp/VERSION names a different carve-lsp commit than the header inside " +
                "lsp/server.js. They are written by the same run of " +
                "tools/build-lsp-bundle.sh, so disagreeing means one of the two was " +
                "regenerated or edited alone.",
            capture(header, Regex("Bundled from markup-carve/carve-lsp commit (\\S+)")),
            fromVersion["carve-lsp"],
        )
        assertEquals(
            "lsp/VERSION names a different carve-js dependency than the header inside " +
                "lsp/server.js.",
            capture(header, Regex("carve-js dependency (.+)"))?.trim(),
            fromVersion["carve-js"],
        )
        assertEquals(
            "lsp/VERSION names a different carve-lsp release than the header inside " +
                "lsp/server.js.",
            capture(header, Regex("carve-lsp release (.+)"))?.trim(),
            fromVersion["carve-lsp-release"],
        )
        assertEquals(
            "lsp/VERSION names a different carve-js release than the header inside " +
                "lsp/server.js.",
            capture(header, Regex("carve-js release (.+)"))?.trim(),
            fromVersion["carve-js-release"],
        )
        assertEquals(
            "lsp/VERSION names a different build time than lsp/server.js.",
            capture(header, BUILT_AT),
            version.first { it.startsWith("built ") }.removePrefix("built ").trim(),
        )
    }

    /** The leading comment block, which is all the provenance ever occupies. */
    private fun headerOf(file: File): List<String> =
        file.useLines { lines -> lines.take(12).takeWhile { it.startsWith("//") || it.isBlank() }.toList() }

    private fun capture(header: List<String>, pattern: Regex): String? =
        header.firstNotNullOfOrNull { pattern.find(it)?.groupValues?.get(1) }

    private fun resource(relative: String): File {
        var dir: File? = File(System.getProperty("user.dir")).absoluteFile
        while (dir != null) {
            val candidate = File(dir, "src/main/resources/$relative")
            if (candidate.isFile) return candidate
            dir = dir.parentFile
        }
        throw AssertionError("src/main/resources/$relative not found from ${System.getProperty("user.dir")}")
    }

    private companion object {
        val BUILT_AT = Regex("Built \\(UTC\\): (\\S+)")
        val ENGINE_REF = Regex("^(commit [0-9a-f]{40}|npm \\d+\\.\\d+\\.\\d+\\S*)$")
        /** A release tag, in either spelling the org uses: `v0.1.4` and `0.1.5`. */
        val RELEASE_REF = Regex("^v?\\d+\\.\\d+\\.\\d+\\S*$")
    }
}
