package org.markupcarve.carve

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Reads the provenance headers the bundle build scripts write.
 *
 * `tools/build-carve-bundle.sh` and `tools/build-lsp-bundle.sh` have always
 * stamped each bundle with the commit it was built from, and until now nothing
 * ever read one back. A recorded provenance no check consumes looks like
 * traceability and cannot fail - the shape catalogued in markup-carve/carve#755
 * - and it is how `carve-js dependency commit unknown` came to sit in a
 * committed bundle: the producer degraded when carve-lsp moved its engine to
 * the registry, and there was no consumer to notice (#62).
 *
 * This is the local, offline half: the header must exist, be well formed, name
 * a real reference, and agree with the sibling `lsp/VERSION` file. Whether those
 * commits are still current upstream is a networked question and lives in
 * `.github/workflows/engine-drift.yml`, which parses the same three lines.
 *
 * Both files are read from the SOURCE TREE rather than the classpath on
 * purpose: `lsp/VERSION` is a build-script output that has to be checked against
 * its own bundle, and comparing two files that were regenerated together is the
 * point.
 */
class CarveBundleProvenanceTest {

    private val sha = Regex("^[0-9a-f]{40}$")

    @Test
    fun previewBundleRecordsTheCarveJsCommitItWasBuiltFrom() {
        val header = headerOf(resource("js/carve.iife.js"))

        assertTrue(
            "carve.iife.js has lost its generator line - rebuild it with " +
                "tools/build-carve-bundle.sh:\n$header",
            header.any { it.contains("Generated by tools/build-carve-bundle.sh") },
        )

        val commit = capture(header, Regex("Bundled from markup-carve/carve-js commit (\\S+)"))
            ?: throw AssertionError(
                "carve.iife.js records no carve-js commit. The header is written by " +
                    "tools/build-carve-bundle.sh; rebuild rather than hand-editing:\n$header",
            )
        assertTrue(
            "carve.iife.js records '$commit' as its carve-js commit, which is not a 40-character " +
                "sha. A placeholder here is exactly the unreadable provenance this test exists " +
                "to reject.",
            sha.matches(commit),
        )
        assertTrue(
            "carve.iife.js records no build timestamp:\n$header",
            capture(header, BUILT_AT) != null,
        )
    }

    @Test
    fun languageServerBundleRecordsBothItsOwnCommitAndTheEngineItCarries() {
        val header = headerOf(resource("lsp/server.js"))

        val lspCommit = capture(header, Regex("Bundled from markup-carve/carve-lsp commit (\\S+)"))
            ?: throw AssertionError("lsp/server.js records no carve-lsp commit:\n$header")
        assertTrue(
            "lsp/server.js records '$lspCommit' as its carve-lsp commit, which is not a 40-character sha.",
            sha.matches(lspCommit),
        )

        // Two legitimate shapes, because carve-lsp has used both: a git
        // dependency (`commit <sha>`) and, since it pinned the engine exactly,
        // a published one (`npm <version>`). Anything else - and in particular
        // the literal `unknown` this field used to degrade to - is a failure.
        val engine = capture(header, Regex("carve-js dependency (.+)"))?.trim()
            ?: throw AssertionError("lsp/server.js records no carve-js dependency:\n$header")
        assertTrue(
            "lsp/server.js records its carve-js dependency as '$engine'. It must be " +
                "'commit <40-hex>' or 'npm <version>' - a placeholder means the build script's " +
                "lockfile probe stopped matching and the provenance is no longer readable.",
            ENGINE_REF.matches(engine),
        )
    }

    @Test
    fun theVersionFileAgreesWithTheBundleItWasWrittenBeside() {
        val header = headerOf(resource("lsp/server.js"))
        val version = resource("lsp/VERSION").readLines().filter { it.isNotBlank() }

        val fromVersion = version.mapNotNull { line ->
            val (key, value) = line.split(' ', limit = 2).let { it[0] to it.getOrElse(1) { "" } }
            if (key == "built") null else key to value.trim()
        }.toMap()

        assertEquals(
            "lsp/VERSION names a different carve-lsp commit than the header inside " +
                "lsp/server.js. They are written by the same run of " +
                "tools/build-lsp-bundle.sh, so disagreeing means one of the two was " +
                "regenerated or edited alone.",
            capture(header, Regex("Bundled from markup-carve/carve-lsp commit (\\S+)")),
            fromVersion["carve-lsp"],
        )
        assertEquals(
            "lsp/VERSION names a different carve-js dependency than the header inside " +
                "lsp/server.js.",
            capture(header, Regex("carve-js dependency (.+)"))?.trim(),
            fromVersion["carve-js"],
        )
        assertEquals(
            "lsp/VERSION names a different build time than lsp/server.js.",
            capture(header, BUILT_AT),
            version.first { it.startsWith("built ") }.removePrefix("built ").trim(),
        )
    }

    /** The leading comment block, which is all the provenance ever occupies. */
    private fun headerOf(file: File): List<String> =
        file.useLines { lines -> lines.take(12).takeWhile { it.startsWith("//") || it.isBlank() }.toList() }

    private fun capture(header: List<String>, pattern: Regex): String? =
        header.firstNotNullOfOrNull { pattern.find(it)?.groupValues?.get(1) }

    private fun resource(relative: String): File {
        var dir: File? = File(System.getProperty("user.dir")).absoluteFile
        while (dir != null) {
            val candidate = File(dir, "src/main/resources/$relative")
            if (candidate.isFile) return candidate
            dir = dir.parentFile
        }
        throw AssertionError("src/main/resources/$relative not found from ${System.getProperty("user.dir")}")
    }

    private companion object {
        val BUILT_AT = Regex("Built \\(UTC\\): (\\S+)")
        val ENGINE_REF = Regex("^(commit [0-9a-f]{40}|npm \\d+\\.\\d+\\.\\d+\\S*)$")
    }
}
