#!/usr/bin/env bash
#
# Regenerates src/main/resources/lsp/server.js from markup-carve/carve-lsp.
#
# carve-lsp is a Node language server (stdio transport). It is not published to
# npm, so this bundles from a local checkout (a sibling of this repo by
# default). esbuild produces a single self-contained CommonJS file with every
# runtime dependency (carve-js, vscode-languageserver, ...) inlined, so the
# plugin only needs a `node` binary on the host - no node_modules to ship.
#
# The plugin launches it as `node <bundledServerDir>/server.js --stdio` through
# lsp4ij.
#
# Usage:
#   tools/build-lsp-bundle.sh [path-to-carve-lsp]
#
set -euo pipefail

here="$(cd "$(dirname "$0")/.." && pwd)"
carve_lsp="${1:-$here/../carve-lsp}"

if [ ! -d "$carve_lsp" ]; then
  echo "carve-lsp checkout not found at $carve_lsp" >&2
  echo "Pass the carve-lsp checkout path explicitly." >&2
  exit 1
fi

# Always rebuild the server from source so the vendored bundle matches the
# checked-out commit. carve-lsp pulls carve-js from git; `npm install` (not
# `npm ci`) is used deliberately so a drifted lockfile still resolves a
# carve-js that exports everything carve-lsp's source imports.
echo "Building carve-lsp in $carve_lsp ..."
(cd "$carve_lsp" && npm install && npm run build)

if [ ! -f "$carve_lsp/dist/server.js" ]; then
  echo "carve-lsp dist not found at $carve_lsp/dist/server.js after build" >&2
  exit 1
fi

out_dir="$here/src/main/resources/lsp"
out="$out_dir/server.js"
mkdir -p "$out_dir"

# Run esbuild from inside the carve-lsp checkout so the module path comments
# and __commonJS keys it emits are checkout-relative (dist/..., node_modules/...)
# instead of embedding machine-local paths from wherever the script happens to
# be invoked.
(cd "$carve_lsp" && npx --yes esbuild dist/server.js \
  --bundle --platform=node --format=cjs --target=node18 \
  --legal-comments=none --outfile="$out")

# Record the carve-lsp commit this bundle was built from, so staleness is
# detectable later (compare against carve-lsp HEAD). Written as a sibling
# VERSION file and prepended as a JS comment in the bundle itself.
carve_lsp_sha="$(git -C "$carve_lsp" rev-parse HEAD 2>/dev/null || echo unknown)"
# The carve-js dependency carve-lsp links against, resolved from its lockfile.
# Two shapes, because carve-lsp has used both: a git tarball URL carrying the
# commit after a `#`, and (since carve-lsp 465a0d5, "pin the engine exactly") a
# plain registry tarball for a published version. Emitted as `commit <40-hex>`
# or `npm <version>`.
#
# This used to read only the `#` fragment and fall back to the literal string
# `unknown`. When carve-lsp switched to the registry the field degraded to
# `unknown` in the committed bundle and nobody noticed, because nothing read the
# header back - the same shape as the drift this file's provenance exists to
# make visible (#62). `unknown` is now a hard failure here, and
# CarveBundleProvenanceTest rejects it on the way in as well.
carve_js_ref="$(node -e '
  const lock = require(process.argv[1] + "/package-lock.json");
  const pkg = lock.packages["node_modules/@markup-carve/carve"];
  if (!pkg) throw new Error("carve-lsp lockfile has no @markup-carve/carve entry");
  const resolved = pkg.resolved || "";
  const frag = resolved.split("#")[1];
  if (frag && /^[0-9a-f]{40}$/.test(frag)) console.log("commit " + frag);
  else if (pkg.version) console.log("npm " + pkg.version);
  else throw new Error("cannot determine the carve-js reference from " + resolved);
' "$carve_lsp")"
built_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

header="// Generated by tools/build-lsp-bundle.sh - do not edit by hand.
// Bundled from markup-carve/carve-lsp commit ${carve_lsp_sha}
// carve-js dependency ${carve_js_ref}
// Built (UTC): ${built_at}
"
# esbuild preserves the source shebang (#!/usr/bin/env node) at the top of the
# bundle. The plugin launches the file as an argument to `node`, never directly,
# so the shebang is dead weight - and a shebang anywhere but the very first line
# is a syntax error. Drop any leading shebang, then prepend the header.
body="$(sed '1{/^#!/d;}' "$out")"
printf '%s\n%s' "$header" "$body" > "$out"

printf 'carve-lsp %s\ncarve-js %s\nbuilt %s\n' "$carve_lsp_sha" "$carve_js_ref" "$built_at" > "$out_dir/VERSION"

# Sanity check: the bundle must be syntactically valid for `node`.
node --check "$out"

echo "Wrote $out (carve-lsp ${carve_lsp_sha})"
