#!/usr/bin/env bash
#
# Regenerates src/main/resources/js/carve.iife.js from @markup-carve/carve.
#
# Carve-js is not published to npm yet, so this bundles from a local checkout of
# the carve-js repo (a sibling of this repo by default). It produces a single
# IIFE that exposes a global `carve` with `carveToHtml(source)`, which the plugin
# runs on GraalJS for preview and HTML export.
#
# Usage:
#   tools/build-carve-bundle.sh [path-to-carve-js]
#
set -euo pipefail

here="$(cd "$(dirname "$0")/.." && pwd)"
carve_js="${1:-$here/../carve-js}"

if [ ! -f "$carve_js/dist/index.js" ]; then
  echo "carve-js dist not found at $carve_js/dist/index.js" >&2
  echo "Pass the carve-js checkout path, and run 'npm ci && npm run build' there first." >&2
  exit 1
fi

out="$here/src/main/resources/js/carve.iife.js"
# Run esbuild from inside the carve-js checkout so the module path comments it
# emits are checkout-relative (dist/...) instead of embedding machine-local
# paths from wherever the script happens to be invoked.
(cd "$carve_js" && npx --yes esbuild dist/index.js \
  --bundle --format=iife --global-name=carve --platform=neutral \
  --legal-comments=none --outfile="$out")

# Record the carve-js commit this bundle was built from, so staleness is
# detectable later (compare against carve-js HEAD). Prepended as a JS comment.
carve_js_sha="$(git -C "$carve_js" rev-parse HEAD 2>/dev/null || echo unknown)"
built_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
header="// Generated by tools/build-carve-bundle.sh - do not edit by hand.
// Bundled from markup-carve/carve-js commit ${carve_js_sha}
// Built (UTC): ${built_at}
"
printf '%s\n%s' "$header" "$(cat "$out")" > "$out"

echo "Wrote $out (carve-js ${carve_js_sha})"
