package org.markupcarve.carve.preview

import com.intellij.openapi.application.PathManager
import com.intellij.openapi.diagnostic.Logger
import java.io.File
import java.security.MessageDigest

/**
 * The preview's third-party browser assets, unpacked onto disk so the page can
 * reference them by `file://` URL.
 *
 * The preview used to pull highlight.js, its two themes, Chart.js, MathJax and
 * Mermaid from `cdn.jsdelivr.net` on every render. That failed silently with no
 * network - unstyled code, no charts, no math, no diagrams - and it made the
 * IDE talk to a third party every time a `.crv` file was opened, which nobody
 * asked it to do. The files now ship inside the plugin; see
 * `resources/preview-assets/VENDOR.md` for versions and licences.
 *
 * ### Why unpack instead of inlining
 *
 * Plugin resources live inside a jar, and a browser cannot read one. The three
 * alternatives were each worse:
 *
 *  * Inlining 5.2 MB of script into the HTML string would re-encode and re-parse
 *    the whole payload on every shell load, and MathJax would still be broken -
 *    its CHTML output finds its webfonts by resolving them against its own
 *    script URL, and an inline script has none.
 *  * A custom CEF scheme handler would work, but it is a second serving path to
 *    keep correct next to the `file://` one the preview already relies on for
 *    relative images.
 *  * Shipping the files beside the jar in the plugin distribution puts them out
 *    of reach of the tests, which is where the path correctness is checked.
 *
 * ### Why the directory is content-addressed
 *
 * The extraction root ends in a digest of `INDEX`, so a plugin update that
 * changes any vendored byte extracts to a NEW directory instead of finding a
 * stale one already there. A version-named directory would have to be right
 * about when a version changed; a digest cannot be wrong about it.
 */
object CarvePreviewAssets {

    private val LOG = Logger.getInstance(CarvePreviewAssets::class.java)

    /** Resource root inside the plugin jar. */
    const val RESOURCE_ROOT: String = "/preview-assets"

    /** Written last, so a half-finished extraction is never mistaken for a finished one. */
    private const val MARKER = ".extracted"

    /** Paths the scaffold references, relative to the extraction root. */
    const val HIGHLIGHT_JS: String = "highlight/highlight.min.js"
    const val HIGHLIGHT_LIGHT_CSS: String = "highlight/github.min.css"
    const val HIGHLIGHT_DARK_CSS: String = "highlight/github-dark.min.css"
    const val CHART_JS: String = "chart/chart.umd.min.js"
    const val MATHJAX_JS: String = "mathjax/tex-mml-chtml.js"
    const val MERMAID_JS: String = "mermaid/mermaid.min.js"

    /** Every asset the preview page loads. The offline test walks exactly this list. */
    val REFERENCED: List<String> = listOf(
        HIGHLIGHT_JS,
        HIGHLIGHT_LIGHT_CSS,
        HIGHLIGHT_DARK_CSS,
        CHART_JS,
        MATHJAX_JS,
        MERMAID_JS,
    )

    /** One entry of `INDEX`: `<sha256> <bytes> <relative path>`. */
    data class Entry(val sha256: String, val size: Long, val path: String)

    /**
     * The vendored file list, read from the jar.
     *
     * A jar has no directory listing, so the set of files to unpack cannot be
     * discovered - it has to be recorded. `tools/vendor-preview-assets.sh`
     * writes `INDEX` and `CarvePreviewAssetsTest` checks it against the source
     * tree, so the list cannot quietly fall behind the files.
     */
    fun index(): List<Entry> {
        val text = readResource("$RESOURCE_ROOT/INDEX")
            ?: error(
                "preview-assets/INDEX is missing from the plugin. It is generated by " +
                    "tools/vendor-preview-assets.sh; without it the preview has no asset list to unpack.",
            )
        return parseIndex(text)
    }

    fun parseIndex(text: String): List<Entry> =
        text.lineSequence()
            .map { it.trim() }
            .filter { it.isNotEmpty() }
            .map { line ->
                // Split on the first two spaces only: a path may contain one.
                val sha = line.substringBefore(' ')
                val rest = line.substringAfter(' ')
                val size = rest.substringBefore(' ')
                val path = rest.substringAfter(' ')
                require(sha.length == 64 && path.isNotEmpty()) { "malformed INDEX line: $line" }
                Entry(sha, size.toLong(), path)
            }
            .toList()

    /**
     * Unpacks every indexed asset under [root], and returns [root].
     *
     * Idempotent: a root whose marker file is already present is left alone, so
     * this costs one `File.exists` on every preview after the first.
     */
    fun extractTo(root: File): File {
        val marker = File(root, MARKER)
        if (marker.isFile) return root

        for (entry in index()) {
            val target = File(root, entry.path)
            target.parentFile?.mkdirs()
            val bytes = readResourceBytes("$RESOURCE_ROOT/${entry.path}")
                ?: error(
                    "preview-assets/${entry.path} is listed in INDEX but not present in the plugin. " +
                        "Re-run tools/vendor-preview-assets.sh.",
                )
            target.writeBytes(bytes)
        }
        marker.writeText("carve preview assets\n")
        return root
    }

    /**
     * The shared extraction root for this build of the plugin, unpacked on first use.
     *
     * Under the IDE's system directory rather than a temp dir: the preview is
     * opened over and over across restarts, and a temp dir that the OS sweeps
     * would silently turn a working preview into an unstyled one.
     */
    fun directory(): File {
        val root = File(PathManager.getSystemPath(), "carve/preview-assets/${digest()}")
        return try {
            extractTo(root)
        } catch (e: Exception) {
            // Degrading here is bad but not fatal - the page still renders text.
            // It must be LOUD, because the failure mode is a preview that looks
            // merely plain rather than broken.
            LOG.error("Could not unpack the preview assets into $root; the preview will render unstyled.", e)
            root
        }
    }

    /** Short digest of `INDEX`, i.e. of every vendored byte, since INDEX carries their hashes. */
    fun digest(): String {
        val text = readResource("$RESOURCE_ROOT/INDEX") ?: return "missing"
        val md = MessageDigest.getInstance("SHA-256")
        return md.digest(text.toByteArray(Charsets.UTF_8)).joinToString("") { "%02x".format(it) }.take(16)
    }

    /**
     * `file://` URL for [root], with a trailing slash, ready to have a relative
     * asset path appended.
     *
     * Built through [File.toURI] rather than string concatenation because a
     * system path containing a space produces an href the browser silently drops
     * - and the resulting preview looks exactly like the offline one this change
     * exists to remove.
     */
    fun baseUrl(root: File): String = root.toURI().toString().removeSuffix("/") + "/"

    private fun readResource(path: String): String? =
        readResourceBytes(path)?.toString(Charsets.UTF_8)

    private fun readResourceBytes(path: String): ByteArray? =
        CarvePreviewAssets::class.java.getResourceAsStream(path)?.use { it.readBytes() }
}
